<?php
//@codingStandardsIgnoreFile

/** @var \Smart\Promotions\Block\ListPromotions $block */

$allPromotions = $block->getCountCollection();
?>

<!DOCTYPE html>
<html lang="vi">
<head>
    <title></title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>
        body{
            color: #333333;
            font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif;
            font-style: normal;
            font-weight: 400;
            line-height: 1.42857143;
            font-size: 1.4rem;
        }
        .promotion-list .items{
            margin-bottom: 15px;
        }
        .promotion-list .items .promotion-item{
            position: relative;
            max-height: 80%;
        }

        .promotion-list .items .promotion-item img{
            border-top-left-radius: 5% 5%;
            border-top-right-radius: 5% 5%;
            border-bottom-right-radius: 5% 5%;
            border-bottom-left-radius: 5% 5%;
        }
        .promotion-list .more-infimation{
            position: absolute;
            bottom: 10%;
            left: 3%;
            width: 100%;
        }
    </style>
</head>
<body>
<?php if ($allPromotions && count($allPromotions) > 0): ?>
    <div class="promotion-list">
        <?php if ($block->getPagerHtml()): ?>
            <div class="toolbar top"><?= $block->getPagerHtml(); ?></div>
        <?php endif ?>
        <div class="items row">
            <?php foreach ($allPromotions as $promo) :?>
                <div class="col-md-6 promotion-item">
                    <a href="<?= $block->getUrl($block::PROMO_URL) . '?id=' . $promo->getId() ?>">
                        <img src="<?= $block->getImageUrl($promo->getImage())?>" alt="" />
                        <span class="more-infimation">
                            <button><?= $block->escapeHtml(__('Xem thêm')) ?></button>
                        </span>
                    </a>
                </div>
            <?php endforeach;?>
        </div>
    </div>
<?php endif;?>
</body>
</html>
